# Numpy :-

(numerical python):-

- Used for working with array.
- In python we have list that serve the purpose of array, but they are slow to proses.
- Numpy is incridible library to performed mathamatical and statistical operation .
- due to its fast and memory effceint  as it is optimized to work with latest cpu architecture.
- Numpy aim is to provide array object that is up to 50x faster than traditionol python list.
- so process can access and manipulate them very effeciently.

In [4]:
# Q:- Write a program to add 10 for each value.
l = [1,2,3,4]
n = []
for i in l :
    n.append(i+10)

print(n)

[11, 12, 13, 14]


In [5]:
import numpy as np
l = [1,2,3,4]
np.array(l)+10

array([11, 12, 13, 14])

In [6]:
# for taking its in list
l = [1,2,3,4]
a = np.array(l)+10
a.tolist()

[11, 12, 13, 14]

In [7]:
# Q :- write a program to add each value in a list1 to list2.
l1 = [1,2,3,4]    # (list 1 number is adding in  list 2 )
l2 = [9,11,6,8]
n = []
for i in range(4):
    c = l1[i]+l2[i]
    n.append(c)

print(n)

[10, 13, 9, 12]


In [8]:
np.array(l1)+np.array(l2)

array([10, 13,  9, 12])

In [9]:
# Q:- write a program to extract the value within the list by using index number using for loop?
l = [34,9,7,81,4,6,2,90,99]
# i want this insex number '0,1,4,5,7'
n = []
for i in [0,1,4,5,7]:
    n.append(l[i])

print(n)

[34, 9, 4, 6, 90]


### Numpy Array :- (nd array)

In [10]:
a = 45
print(a)
print(type(a))

45
<class 'int'>


In [11]:
a = 45
arr_0 = np.array(a)
print(arr_0)
print(type(a))

45
<class 'int'>


In [12]:
arr_0.ndim

0

In [13]:
arr_0.shape

()

In [14]:
# if there is empty tumple its mean it is zero dimentionol array.

In [15]:
a = [1,2,3,4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [16]:
arr_1 = np.array(a)
print(arr_1)
print(type(arr_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [17]:
c = 'srk'
print(c) # here it is not printing it with coted bescuse we use printing function here

srk


In [18]:
c

'srk'

In [19]:
c= np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [20]:
c

array([1, 2, 3, 4])

In [21]:
arr_1

array([1, 2, 3, 4])

In [22]:
arr_1.ndim

1

In [23]:
arr_1.shape

(4,)

In [24]:
# shape will always be tuple

## Function for creting 1D array

### * Arange :-

- Arange is an array value version of the build in python range function.
- Array with range of values.
- syntex :- np.arange(start,end,step) example (0, 10 , 2).

In [25]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


### * linspace :-

- Return evenly spaeced number over a specific interval.
- syntex :- np.linspace(start,end,num_of_sample)

In [26]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [27]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [28]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

### * Zeros :-

- Genral array of zeros.
- syntex:- np.zeros(shape).

In [29]:
np.zeros((4,))

array([0., 0., 0., 0.])

In [30]:
# if we want int datatype value
np.zeros((4),dtype = int)

array([0, 0, 0, 0])

### * Ones :-

- Genrate array of ones.
- syntex :- np.ones(shape).

In [31]:
np.ones((4,))

array([1., 1., 1., 1.])

### * Random.randint :-

- Return a random integer from starte (inculsive) to end (enclusive).
- syntex :- np.random.randint(start, end, num_of_sample).

In [32]:
np.random.randint(1, 1000, 5)

array([509, 912,  17, 663, 484])

In [33]:
np.random.randint(1, 1000, 5)

array([553, 105, 146, 423, 337])

### Accesing element Extracting the value.

- 1:- accessing a single value through index.
- 2:- accessing a multiple value based on slicing.
- 3:- accessing a multiple value based on index.
- 4:- accesing a multiple value based on condition.

In [34]:
a = np.array([100,120,130,190,200,14,18,26])
print(a)

[100 120 130 190 200  14  18  26]


 1 :- accessing a single value through indexing.

In [35]:
# positive index
a[1]

120

In [36]:
# negative index
a[-1]

26

 2:- accessing a multiple value based on slicing.

In [37]:
a[0:5:2]

array([100, 130, 200])

In [38]:
a[0:5:1]

array([100, 120, 130, 190, 200])

 3:- accessing multiple value based on indexing.

In [39]:
# syntex:- array[list of index number]
a [[0,1,5,6,4]]

array([100, 120,  14,  18, 200])

In [40]:
# we can also repeat indexing
a[[0,1,5,6,4,0,0,0,0]] # becuse list accept dupllicates.

array([100, 120,  14,  18, 200, 100, 100, 100, 100])

In [41]:
# with the  help of loop or this is backed code.
l = [100,120,130,190,200,14,18,26]
n = []
for i in [0,1,5,6,4,0,0,0,0]:
    n.append(l[i])

print(n)

[100, 120, 14, 18, 200, 100, 100, 100, 100]


4:- Accesing a multiple value based on condition (Mask indexing or fancy indexing)

In [42]:
# syntex :- array [condition]
# first it will cheak the condition (mean which item gives True for the condition that item will be selected.)

a = np.array([45,46,47])
a > 45

array([False,  True,  True])

In [43]:
# if i want data 
a = np.array([45,46,47])
a[a > 45]

array([46, 47])

## Modify the value in numpy

In [44]:
# Add a single in a array
# sytex : np.append(array,value)

a = np.array ([45,46,47])
a1 = np.append(a,110)
print(a1)

[ 45  46  47 110]


In [45]:
# adding a multiple value  
a = np.array([45,46,47])
a2 = np.append(a,[140,129,130])
print(a)

[45 46 47]


### Replacing a single value in a 1D array

In [46]:
a = np.array([45,46,47])
a[1] = 100

In [47]:
print(a)

[ 45 100  47]


### Replacing a multiple value with a single value in a array.

In [48]:
a [[1,2]]=15
a

array([45, 15, 15])

In [49]:
a [[1,2]]=15,16
a

array([45, 15, 16])

### Replacing a multiple value with a multiple values in a array

In [50]:
a[[1,2]] =[150,200]
a

array([ 45, 150, 200])

### delet a single value in a array

In [51]:
# syntex :- np.delete(array,indexnumber)
a = np.array([1,2,3,4])
np.delete(a,1)  # it will the index number value

array([1, 3, 4])

### Delete multiple value in a array

In [52]:
#syntex :- np.delete(array,[multiple index number])
a4 = np.delete(a,[1,2])
print(a4)  # so it have deleted index numbers values

[1 4]


### Copy array

In [53]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


### Sorting an array :-

In [54]:
a = np.array([4,6,8,2,1])
b = np.sort(a)
print(b)

[1 2 4 6 8]


##### imp Notes :- for padas backend codes is numpy and for numpy backend code is list.

### Operations :-

- Arthmetic operations:-

In [55]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [56]:
b = a + 1  # we are adding here 1 value 
print(b)

[2 3 4 5]


In [57]:
c = a + 0
print(c)

[1 2 3 4]


In [58]:
d = a ** 2
print(d)

[ 1  4  9 16]


In [59]:
print(a+b)

[3 5 7 9]


In [60]:
print(a-b)

[-1 -1 -1 -1]


In [61]:
print(a*b)

[ 2  6 12 20]


- comparision operations :-

In [62]:
a == b

array([False, False, False, False])

In [63]:
b >= a

array([ True,  True,  True,  True])

In [64]:
np.array_equal(a,b) # it will cheak each value a and b is same or not

False

In [65]:
np.array_equal(a,c)

True

In [66]:
a = np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [67]:
np.log(a)
# this is warning wherever you are getting output as infinite it will give you waring.

C:\Users\ARSHAD ALI KHAN\AppData\Local\Temp\ipykernel_9552\2037733980.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [68]:
# solution of a waring
import warnings
warnings.simplefilter("ignore")

In [69]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# 2 D numpy Array :-

- 2 D (dimentinol) mean rows and columns simply it's matrix.

In [70]:
import numpy as np
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
# // OR 

In [72]:
f = np.array ([[1,2,3],[4,5,6]])

In [73]:
f  # it is 2 by 2 matrix (2*2)

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.array([[1,2,3],[4,5,6],[7,8,9]])
# it is 3 by 3 matrix (3*3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# nul value mean missing value or not available.

In [76]:
b = np.array([[0,1,2,5],[2,3,4,8]])
print(b)

[[0 1 2 5]
 [2 3 4 8]]


In [77]:
b.shape

(2, 4)

#### imp notes :-

- one dimentinol array starte with one bracket ([]).
- Two dimentinol array starte with two bracket ([[]]).
- and Three dimentinol array starte with Three bracket ([[[]]]).
- if you combine 3 to 2 dimentionol array it become three dimentinol.

In [78]:
np.zeros((3,3))  # it is flout value 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.zeros((3,3),dtype = int) # now it is int value

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.ones((3,3))+1  # we can add any number from adding here.

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [82]:
np.ones((3,3),dtype = int) +1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

### * Identity matrix :-

- only diagnol value will be and except all is zeros .

In [83]:
np.eye(3,3)
# daignol mean cross value 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- wherever the number of rows == number of columns is called sqaure matrix.
- wherever number of row not = number of columns is called rectangular matrix.

### * Diagonal matrix :-

In [84]:
np.diag ([1,8,14])  # we can give daignol value by ourselve.

array([[ 1,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 14]])

In [85]:
# Extracting daignol value
a = np.array ([[1,2,3],[3,4,5],[9,8,9]])
np.diag(a)

array([1, 4, 9])

In [86]:
a = np.array([[1,2,3],[3,4,5]])
np.diag(a)

array([1, 4])

In [102]:
a = np.array([[10,20,50],[30,40,60],[20,80,90]])

In [103]:
print(a)

[[10 20 50]
 [30 40 60]
 [20 80 90]]


### * indexing of 2 D array :-

In [104]:
a[0] 

array([10, 20, 50])

In [105]:
a[2,2]

90

In [ ]:
# To extract single value from 2D array
# syntex :- array_name[rows index number, columns index number]

In [109]:
a[1,2]

60

In [110]:
# To extract a single row 
a[2]

array([20, 80, 90])

In [106]:
# To extract multiple value
a[1:3]

array([[30, 40, 60],
       [20, 80, 90]])

In [108]:
a[0:2]

array([[10, 20, 50],
       [30, 40, 60]])

In [98]:
# replace a single value in 2D array.
print(a)

[[[10 20 50]
  [30 40 60]
  [20 80 90]]]


In [111]:
a[2,2] = 500

In [112]:
a   # here we replace a single value

array([[ 10,  20,  50],
       [ 30,  40,  60],
       [ 20,  80, 500]])

In [113]:
# replacing entire row
a[1] = [25,30,60]
a

array([[ 10,  20,  50],
       [ 25,  30,  60],
       [ 20,  80, 500]])

### * Flattening :- 

. coverting 2D to 1D is called flattening.

In [116]:
a = np.array([[0,1,2],[3,4,5]])
print(a)
b = a.ravel()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


### * Repashe array :-

- converting one shape to other shape.

In [118]:
arr = np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [119]:
a1 = arr.reshape(2,3)
print(a1)
# (2,3) :- mean 2row and 3cols

[[0 1 2]
 [3 4 5]]


In [120]:
a1 = arr.reshape(6,1)  # it is six rows and one cols
print(a1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [121]:
a = np.array([[0,1,5],[10,50,8]])
print(a)
print(a.shape)

[[ 0  1  5]
 [10 50  8]]
(2, 3)


In [125]:
print(a.reshape(3,2))

[[ 0  1]
 [ 5 10]
 [50  8]]


### * Sort :-

- sortinh along as axis.
- axis=1-->row & axis=0-->column

In [126]:
a = np.array([[5,4,6],[2,8,2],[8,9,20]])
b = np.sort(a,axis = 1)
b   # it also priting in order.

array([[ 4,  5,  6],
       [ 2,  2,  8],
       [ 8,  9, 20]])

In [127]:
# Now columns wise
a = np.array([[5,4,6],[2,8,2],[8,9,20]])
b = np.sort(a,axis=0)
b

array([[ 2,  4,  2],
       [ 5,  8,  6],
       [ 8,  9, 20]])

### * Mathametical operatoins:-

In [131]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[40,4],[14,24],[34,44]])
# adding a and b (element wise addition).
print(a+b)

[[41  6]
 [17 28]
 [39 50]]


In [132]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [133]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# matrix multiplication
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

### * join multiple 2D array

In [134]:
np.concatenate((a,b),axis =0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [135]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [136]:
# Invertcal stack
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [137]:
# In horizantal stack
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

--------end-------numpy-------